filebeat.inputs:
- type: log
  enabled: true
  paths:
    - logs/app.log

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1

setup.kibana:

  host: "localhost:5601"

output.logstash:
  # The Logstash hosts
  hosts: ["localhost:5044"]

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
  - drop_fields:
      fields: ["agent.ephemeral_id", "agent.hostname", "agent.id", "agent.type", "agent.version", "ecs.version", "input.type", "log.offset", "version", "host.architecture", "host.hostname", "host.ip", "host.mac", "host.name", "host.os.build", "host.os.family", "host.os.kernel", "host.os.name", "host.os.platform", "host.os.version", "@version", "host.id"]
